spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_DATABASE}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
